# Generated by Django 4.1.7 on 2023-02-22 22:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('credit', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=150, null=True, region=None)),
                ('amount', models.PositiveIntegerField(editable=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.seller')),
            ],
        ),
    ]
